name: 'Terraform CI'

on:
  push:
    branches:
    - main
    paths: ['terraform/**']
  
  workflow_dispatch:

env:
  TERRAFORM_VERSION: "1.2.9"
  TF_IN_AUTOMATION: "True"
  TF_VAR_project_id: ${{ secrets.GKE_PROJECT }}

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Terraform Apply
        uses: ./.github/apply
        with:
          terraform_directory: "terraform"
          terraform_sa: ${{ secrets.TF_SA }}
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          google_sa_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
