name: 'Terraform CI'

on:
  push:
    branches:
    - main
    paths: ['terraform/**']
  
  workflow_dispatch:

env:
  TERRAFORM_VERSION: "1.2.9"
  TF_IN_AUTOMATION: "True"
  TF_VAR_project_id: ${{ secrets.GKE_PROJECT }}

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraforom_version }}
          terraform_wrapper: false

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: ${{ secrets.TF_SA }}
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0.6.0'

      - name: Terraform Init
        id: init
        working-directory: terraform
        shell: bash
        run: |
          terraform init
      
      - name: Terraform Plan
        id: plan
        working-directory: terraform
        shell: bash
        run: |
          echo 'plan<<EOF' >> $GITHUB_OUTPUT
          terraform plan -no-color -out=tfplan >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      
      - name: Terraform  apply
        id: apply
        working-directory: terraform
        shell: bash
        run: |
          terraform apply -auto-approve -no-color tfplan